---
title: "Models"
description: "R packages, Shiny apps, and other open-software projects."
format:
  html:
    page-layout: full
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  echo= FALSE,
  out.width = "100%"
)
```

```{css, echo=FALSE}
.quarto-title {
    display: none;
  }

.description {
    display: none;
  }
```


# Models are cool!

This page catalogs a variety of numerical modeling tools for conducting ecological, engineering, and decision support analyses. The tools appear in multiple formats (e.g., R packages, Shiny Apps, spreadsheets, etc.). Each model is briefly described along with links to more details resources (i.e., documents, repos, packages, web apps). 

Models were developed with many partners and collaborators, and model documentation includes points of contact for each tool. In particular, many of these models were developed with two teams from the U.S. Army Engineer Research and Development Center's (ERDC) Environmental Laboratory (EL): the Water Research Integrating Socio-ecological and Engineered Systems (WRISES) team and the [Integrated Ecological Modeling team](https://ecomod.erdc.dren.mil/). Their contributions are gratefully acknowledged, but the presence of tools here does not reflect their endorsement.


------------------------------------------------------------------------

## Ecological Modeling and Assessment

------------------------------------------------------------------------

Many of these tools focus on assessing or forecasting ecological condition. Most of these models were designed to support ecosystem restoration decisions within the U.S. Army Corps of Engineers.

**ecorest**

Habitat suitability models are a common tool for informing ecosystem restoration. These models have a generalized index-based structure, where habitat quantity and quality are assessed separately. Quantity is usually quantified as area but may also be considered in terms of length (e.g., stream miles) or volume. Habitat quality is then assessed on a zero to one scale from unsuitable to optimal, respectively. Quality is assessed relative to different physical and biological co-variates to estimate suitability indices, and then multiple co-variates are aggregated into an overarching habitat suitability index (HSI). The `ecorest` R-package provides a generalized platform for conducting habitat suitability analyses. The package also includes data for 347 existing habitat models proposed by the U.S. Fish and Wildlife Service in the 1980s (the so-called "blue books").

- [ecorest R-package](https://cran.r-project.org/web/packages/ecorest/)  
- [web application](https://wrises.shinyapps.io/ecorest-webapp/)  
- [repo for web application](https://github.com/USACE-WRISES/ecorest-webapp)


**Geospatial Suitability Index Toolbox (GSI)**

The Geospatial Suitability Indices Toolbox (GSI Toolbox) provides an ArcGIS Pro toolbox for executing habitat suitability models. The tool provides a comparable set of algorithms to 'ecorest', but the numerical models are executed within a a raster-based geospatial environment.

- [ERDC Technical Report SR-22-4](https://erdc-library.erdc.dren.mil/bitstreams/63c6c2a8-e005-4727-b8fc-97c1c768a402/download)(Saltus et al. 2022)  
- [GIS Toolbox](https://dx.doi.org/10.21079/11681/41881)


**Riparian Ecological Functions Index (REFI)**

Riparian zones are important transitional areas between upland and stream ecosystems that improve water quality, provide ecological habitat and corridors, maintain natural hydrologic processes, and provide other important ecosystem goods and services. U.S. Army Corps of Engineers’ actions often affect riparian ecosystem structure and function such as ecological benefits associated with stream restoration projects and impacts associated with levee management. While some regional assessment procedures are available, practitioners lack broadly applicable models and tools for assessing riparian ecosystem condition. The Riparian Ecological Function Index (REFI) is a semi-quantitative, rapid assessment technique intended for nationwide use. This model is structured around three major ecological functions of riparian zones: (1) the riparian zone’s effect on instream outcomes, (2) its role in ecological connectivity, (3) how it provides unique and important habitats for a variety of taxa. 

- The model is currently being reviewed for USACE certification.  
- Model documentation is also in review as an ERDC Technical Report.  
- A model overview was provided in an [EMRRP Webinar](https://emrrp.el.erdc.dren.mil/webinars.html) on January 29, 2024.  
- A beta version of REFI was applied in the [Utoy Creek ecosystem restoration study](https://www.mdpi.com/2073-445X/14/3/449).


**Web Application for Riparian Models (WARM)**

Riparian zones are important transitional areas between upland and stream ecosystems that improve water quality, provide ecological habitat and corridors, maintain natural hydrologic processes, and provide important ecosystem goods and services. While many riparian models exist, they often are challenging to find in grey literature and may not have analytical tools and calculators readily available for other users. This model compiles nine riparian models into a web application for accessing these tools. This project embraces the principles of open science by increasing the accessibility and practicality of existing scientific models. For instance, our web interface helps practitioners locate hard-to-find models, select among models for a particular application, and execute the models with error-checked calculators. The application also increases the long-term shareability of these riparian models through platforming that publicly shares computational code (i.e., through online repositories), reduces barriers to entry for analysts (e.g., programming literacy), and increases ease of use, all of which save time and money.

- [Web application](https://wrises.shinyapps.io/warm/) is currently being reviewed for USACE certification.  
- [repo for web application](https://github.com/USACE-WRISES/riparian.webapp)  
- [Conference paper](https://ascelibrary.org/doi/10.1061/9780784485163.024) summarizing the approach.  
- Model documentation is also in review as an ERDC Technical Note.  
- [ERDC technical note](https://dx.doi.org/10.21079/11681/47706) summarizing existing riparian models.  
- A model overview was provided in an [EMRRP Webinar](https://emrrp.el.erdc.dren.mil/webinars.html) on January 31, 2024.  


**Watershed Upstream Connectivity Toolkit (WUCT)**

This model provides a procedure for quantifying benefits associated with removal of organism movement barriers within a watershed (e.g., dam removal, culvert repair, fish ladder installation) or impacts of barrier addition (e.g., dam construction, weir installation). The model focuses on upstream movement of migratory organisms such as fish and is intended for application at the watershed-scale. The algorithm is based on four primary components: habitat quantity upstream of a dam, habitat quality upstream of a dam, the passability of a structure for a given organism, and the shape/topology of the watershed. This algorithm combines these data to estimate quality-weighted, accessible habitat at the watershed scale. 

- [GitHub repo](https://github.com/USACE-WRISES/WUCT)
- [Model documentation](https://github.com/USACE-WRISES/WUCT/blob/main/Instructions/README.md)  
- Model applications in the Truckee River (NV), Duck-Buffalo watershed (TN), Bronx River (NY), Hudson River Valley (NY), and Proctor Creek (GA).  
- Model structure is described in a series of papers documenting the [network theory](https://esajournals.onlinelibrary.wiley.com/doi/abs/10.1890/12-1564.1), the role of network metrics in [connectivity prioritization](https://onlinelibrary.wiley.com/doi/abs/10.1002/rra.3021), and [selection of barrier prioritization methods](https://onlinelibrary.wiley.com/doi/full/10.1002/rra.3684).


**Proctor Creek Ecological Model (PCEM)**

In partnership with the City of Atlanta and thirteen federal agencies, the Mobile District (SAM) of the U.S. Army Corps of Engineers (USACE) developed a feasibility study for urban stream restoration in Proctor Creek, Atlanta, Georgia. A two-part numerical modeling toolkit, the Proctor Creek Ecological Model (PCEM), was developed to support planning of this ecosystem restoration project. In both phases, PCEM contains four modules related to instream condition, riparian condition, hydrologic change, and watershed connectivity, which are combined into an overarching assessment of stream ecosystem integrity at the watershed-scale. 

- [Phase 1 modeling report](https://dx.doi.org/10.21079/11681/29514)  
- [Phase 2 modeling report](https://dx.doi.org/10.21079/11681/29515)


**New York Bight Ecological Model (NYBEM)**

The U.S. Army Corps of Engineers (USACE) is conducting three large-scale coastal storm risk management feasibility studies in the New York Bight ecosystem, specifically: the New Jersey Back Bays, the New York-New Jersey Harbor & Tributaries Study, and the Nassau County Back Bays. In these study areas, the USACE is considering a diversity of measures for mitigating flood risks, including structural actions (e.g., levees, floodwalls, storm surge barriers), non-structural measures (e.g., buy-outs, elevation of structures, flood-proofing), and natural and nature-based features (e.g., wetland creation, reefs for breakwaters). The New York Bight Ecological Model (NYBEM) is being developed as a tool for partially assessing the direct and indirect effects of agency actions on regional ecosystems. The NYBEM assesses changes in habitat quantity and quality associated with changing hydrodynamic conditions in six major ecosystem types: freshwater tidal, estuarine intertidal, estuarine subtidal, marine intertidal, marine subtidal, and marine deepwater. The numerical code for NYBEM was programmed in the R Statistical Software Language, and the model code is contained within an R-package (`nybem`). 

- [Online model documentation](https://mvr-gis.github.io/NYBEM-Report/) that is currently in review for USACE certification.  
- [R-package](https://github.com/MVR-GIS/nybem) containing all model code.


**Simple Model for Urban Riparian Function (SMURF)**

Stream assessment tools have been developed for rapid application and restoration prioritization in urban streams. While these models typically include riparian variables, they are often inherently focused on in-channel outcomes. The Simple Model for Urban Riparian Function (SMURF) is designed as a rapid assessment technique for highly urbanized environments. Three major categories of outputs are addressed: (1) indirect effects of riparian zones on instream processes, (2) riparian areas as important providers of native faunal habitat, and (3) riparian zones as ecological corridors and sources of resilience in highly disturbed areas. The model uses a combination of rapid field assessment protocols and desktop geospatial assessments applied independently to left and right banks. The SMURF was developed and applied in the context of the Beargrass Creek ecosystem restoration study in Louisville, Kentucky; however, the modeling approach is adaptable to other urban riparian zones.  

- Model documentation in review as ERDC Technical Report  
- Model code available upon request from WRISES  
- Model application in the [Beargrass Creek ecosystem restoration feasibility study](https://www.lrd.usace.army.mil/Missions/Projects/Article/3637533/three-forks-of-beargrass-creek-ecosystem-restoration-feasibility-study/)  
- Model evaluation was conducted relative to vegetation monitoring data, which will be documented in a forthcoming ERDC Technical Note. 


**Qualitative Habitat Evaluation Index for Louisville Streams (QHEILS)**

Urban stream restoration typically involves multiple objectives addressing different aspects of ecosystem integrity, such as habitat provision, geomorphic condition, watershed connectivity, water quality, and land-use change. Multiple stream assessment tools and models have been developed and applied to inform restoration prioritization, planning, and design. The Qualitative Habitat Evaluation Index for Louisville Streams (QHEILS, pronounced “quails”) was designed as an interdisciplinary assessment method for urban streams in the Louisville, Kentucky, metropolitan region. The model adapts a regional habitat assessment procedure, the Qualitative Habitat Evaluation Index (QHEI), by incorporating additional processes related to geomorphic change and watershed connectivity. 

- [ERDC Technical Note](https://dx.doi.org/10.21079/11681/48759) containing model documentation and associated R script.


**Rio Grande Silvery Minnow Population Tool**

To estimate Rio Grande Silvery Minnow recruitment under different hydrologic, restoration, and management scenarios, we first built a 2-D hydraulic model that estimated floodplain inundation extent within the Middle Rio Grande at seven discharges between 700 and 7,000 cfs. To quantify the relationship between inundation and recruitment, we used a sophisticated RGSM population model ([Yackulic et al. 2022](https://esajournals.onlinelibrary.wiley.com/doi/10.1002/ecs2.4240)) that integrates fish monitoring data, hydrologic data, and expert elicitation of RGSM spawning parameters, but does not include absolute amounts of habitat so cannot be used to estimate recruitment expected from specific restoration projects. We created new versions of this population model that incorporate our floodplain inundation estimates, and then used out-of-sample RGSM monitoring data to validate our results. This model therefore estimates the empirical relationship between amount of inundation and the number of RGSM that are recruited to the population in spring. Using this estimate, we are then able to generate estimates of RGSM recruitment under different restoration and hydrologic scenarios at different discharge levels. The model is presented in a simple to use web application.

- [Web application](https://wrises.shinyapps.io/rgsm-recruit/)


**riverweed**

Aquatic macrophyte provide a uniqe array of ecological functions ranging from nutrient uptake to provision of invertebrate and fish habitat. This model provides a suite of functions and algorithms for estimating growth of aquatic macrophytes. The model was designed around hornleaf riverweed (*Podostemum ceratophyllum*), but the general procedures could be adapted to other macrophytes.

- [`riverweed` R-package](https://github.com/USACE-WRISES/riverweed)  
- Models are currently be documented in a journal paper.  


------------------------------------------------------------------------

## Hydraulic and Hydrologic Modeling

------------------------------------------------------------------------

Understanding ecological dynamics often requires linking with models of physical processes. The following tools assess physical processes with a particular emphasis on hydraulic and hydrologic modeling.  


**HYDraulic ROughness CALculator (HYDROCAL)**

The ability to quantify the influence of vegetation on channel and floodplain hydraulics, in particular hydraulic roughness, is critical for flood control concerns; however, diversity of vegetation type and behavior makes this parameter very difficult to quantify repeatedly and accurately. HYDROCAL combines a number of methods for estimating roughness into a single user-interface. The model was originally programmed in Excel, but has been subsequently recoded in R and served through a web application.

- [ERDC Technical Note](https://hdl.handle.net/11681/2034) documenting original model theory and goals.  
- [R-package](https://cran.r-project.org/package=HYDROCAL)  
- [Web application](https://wrises.shinyapps.io/hydrocal/)


**Rapid Hydraulic Assessment (RHA)**

The planning, design, and installation of a stream restoration project must take into account the hydraulic conditions of the stream being restored. Even a cursory review of channel hydraulics can increase the probability of achieving successful restoration outcomes. This technical note briefly reviews key issues in hydraulic classification, presents preliminary hydraulic analyses common to most stream restoration projects, and discusses a set of simple tools for first-order, rapid hydraulic analyses. The Rapid Hydraulic Assessment toolkit provides two modules for estimating single cross-section channel hydraulics at normal flow conditions.

- [ERDC Technical Note](https://hdl.handle.net/11681/4038) on simple hydraulic analysis  
- [Trapezoidal cross-section tool](https://cw-environment.erdc.dren.mil/cwmg/rha/RHA-Trap.html)  
- [Irregular cross-section tool](https://cw-environment.erdc.dren.mil/cwmg/rha/RHA-Cross.html)


**eRAMS Flow Analysis**

Colorado State's [eRAMS modeling platform](https://erams.com/catena/) provides a diverse suite of tools for environmental analysis in a simple to use geospatial interface. ERDC partnered with Colorado State on models for real-time analysis of USGS streamflow gage data. Models automate standard hydrologic analyses from Bulletin 17B, provide novel visualization methods for displaying streamflow data, and provide a mechanism for computing environmental flow metrics.  

- [eRAMS flow analysis tools](https://erams.com/flowanalysis)


------------------------------------------------------------------------

## Decision Support Tools

------------------------------------------------------------------------

Much of my work focuses on application of models to inform ecosystem restoration and flood risk management projects. These efforts often include decision support modeling that synthesizes ecological outcomes with cost estimates and other factors.


**ecorest (again?!)**

The U.S. Army Corps of Engineers (USACE) engages in a large variety of decisions affecting ecological outcomes such as ecosystem restoration of oyster reefs, environmental flows for imperiled fishes, and bird breeding grounds impacted by dredge material management. Many models can be used to assess ecological outcomes of these project (see examples above). These ecological outcomes are often combined with cost estimates to inform decision making. In addition to the habitat modeling features described above, `ecorest` also includes a suite of decision support tools for conducting cost-effectiveness and incremental cost analyses. These tools mirror procedures from [IWR Planning Suite](http://www.iwr.usace.army.mil/Missions/Economics/IWR-Planning-Suite/), but they are intended for different use case such as rapid analyses with a web application or detailed simulations coupled with other R-based ecological modeling algorithms. 

- [ecorest R-package](https://cran.r-project.org/web/packages/ecorest/)  
- [web application](https://wrises.shinyapps.io/ecorest-webapp/)  
- [repo for web application](https://github.com/USACE-WRISES/ecorest-webapp)
- [preliminary model documentation](https://usace-wrises.github.io/ecorest.documentation/)


**EngrEcon**

Water resource engineering and ecosystem restoration projects typically require economic analysis of the costs and benefits of alternative actions. However, costs may not be distributed evenly over a project's life cycle and may include initial capital investments, short-term adaptive management actions, long-term operations and maintenance, and eventually disposal (e.g., de-construction, removal, or de-commissioning). Engineering economics methods exist to convert cost between present, future, and annualized costs to inform life cycle planning. Life cycle cost analysis may be particularly important when comparing projects with dramatically different investments through time (e.g., an operationally intensive conventional infrastructure system vs. a larger capital investment in natural infrastructure). The `EngrEcon` toolkit provides a suite of functions and methods for executing standard engineering economics calculations such as cost conversion, cash flow analysis, and life cycle cost analysis. A set of analytical functions was programmed in the R Statistical Software Language and bundled together in a globally available R package. Additionally, a web application was developed to reduce barriers to entry for users without programming experience. 

- [`EngrEcon` R-package](https://cran.r-project.org/web/packages/EngrEcon/index.html)  
- [Web application](https://wrises.shinyapps.io/engrecon-webapp/)  
- Model documentation is currently being reviewed for USACE certification.  


**Dam Removal Cost Estimator**

Dam removal has grown into a common action for both river restoration and infrastructure asset management. This tool provides a method for estimating monetary costs of dam removal project. The models are based on 668 dam removal projects and driven by a machine learning algorithm. A web application provides a simple use interface for model access.

- [Web application](https://wrises.shinyapps.io/DamRemovalCostPredictiveModel/)  
- [Journal paper](https://www.frontiersin.org/journals/ecology-and-evolution/articles/10.3389/fevo.2023.1215471/full) presenting model background and data  
- [Cost engineering report](https://www.usgs.gov/publications/dam-removal-cost-databases-and-drivers) to guide cost estimation procedures for dam removal


**Utoy Creek Decision Support Models**

In partnership with the City of Atlanta, the USACE’s Mobile District is leading a feasibility study of potential stream restoration actions in the Utoy Creek watershed. The study is authorized through the USACE’s continuing authorities program (CAP) for aquatic ecosystem restoration (Section 206, WRDA 1996). This decision support model and associated report presents cost-effectiveness and incremental cost analyses (CEICA) to guide development of the agency’s recommended restoration plan as well as demographic analysis of communities affected by the recommend plan. The report applies CEICA in multiple contexts to inform decisions in the Utoy Creek watershed as the project proceeds from site screening to site-scale justification to watershed-scale portfolio analysis. 

- [Online report](https://usace-wrises.github.io/UtoyDecisions/)
- [GitHub repo](https://github.com/USACE-WRISES/UtoyDecisions)

